source "https://rubygems.org"

gem "calabash-cucumber", :github => "calabash/calabash-ios", :branch => "develop"
gem "cucumber", "2.99.0"
gem "run_loop", :github => "calabash/run_loop", :branch => "v-malob/xcode-10-3"
gem "json", "1.8.6"

# Sync with config/xtc-other-gems
gem "rspec", "~> 3.0"
gem "xamarin-test-cloud", "~> 2.0"

gem "pry"
gem "pry-nav"

# Used to submit develop versions of calabash-cucumber and run-loop to XTC
gem "briar", "~> 2.0"
gem "luffa"

