source "https://rubygems.org"

gem "calabash-cucumber", :github => "calabash/calabash-ios", :branch => "develop"
gem "run_loop", :github => "calabash/run_loop", :branch => "develop"

# Easy expections; no screenshots
gem "rspec", "~> 3.0"

gem "pry"
gem "pry-nav"

# For `briar xtc submit < device set > [profile]
gem "briar", ">= 1.4.2", "< 2.0"

