source "https://rubygems.org"

gem "calabash-cucumber", :github => "calabash/calabash-ios", :branch => "develop"
gem "run_loop", :github => "calabash/run_loop", :branch => "develop"

# Easy expections; no screenshots
gem "rspec", "~> 3.0"

gem "pry"
gem "pry-nav"

# Submit develop versions of calabash-cucumber and run-loop to XTC
gem "briar", ">= 1.4.2", "< 2.0"
gem "luffa"

