#!/usr/bin/env ruby

require File.expand_path(File.join(File.dirname(__FILE__), '..', 'test-helpers'))

working_dir = File.expand_path(File.join(File.dirname(__FILE__), '..', '..'))

Dir.chdir working_dir do
  env_vars = {}
  do_system('make clean')
  do_system('scripts/test/test-make-without-xcpretty.rb', {:env_vars => env_vars})

  install_gem('xcpretty')

  do_system('make clean')
  do_system('scripts/test/test-make-rules.rb', {:env_vars => env_vars})
  do_system('scripts/test/xctest.rb', {:env_vars => env_vars})
  do_system('scripts/test/run-chou-tests.rb', {:env_vars => env_vars})
end
